/** Дополнительные CRM-клиенты (не демо-логины). Пароли случайные, в кабинет ими не входят. */
export const CRM_CLIENTS = [
  {
    key: 'anna',
    email: 'anna.sokolova@example.local',
    fullName: 'Анна Соколова',
    phone: '+79991234001',
    city: 'Москва',
    telegram: '@anna_sokolova',
  },
  {
    key: 'sergey',
    email: 'sergey.volkov@example.local',
    fullName: 'Сергей Волков',
    phone: '+79991234002',
    city: 'Химки',
    telegram: '@volkov_srv',
  },
  {
    key: 'maria',
    email: 'maria.kuznetsova@example.local',
    fullName: 'Мария Кузнецова',
    phone: '+79991234003',
    city: 'Москва',
    telegram: null,
  },
  {
    key: 'dmitry',
    email: 'dmitry.novikov@example.local',
    fullName: 'Дмитрий Новиков',
    phone: '+79991234004',
    city: 'Мытищи',
    telegram: '@novikov_d',
  },
  {
    key: 'elena',
    email: 'elena.morozova@example.local',
    fullName: 'Елена Морозова',
    phone: '+79991234005',
    city: 'Реутов',
    telegram: null,
  },
  {
    key: 'oleg',
    email: 'oleg.belov@example.local',
    fullName: 'Олег Белов',
    phone: '+79991234006',
    city: 'Москва',
    telegram: null,
    blocked: true,
  },
];

export const LEGACY_DEMO_EMAILS = [
  'anna.client@example.local',
  'sergey.client@example.local',
  'manager2@example.local',
];

function dx({ summary, urgency = 'medium', confidence, cost, causes, checks }) {
  return {
    summary,
    urgency,
    confidence,
    estimated_cost_from: cost,
    probable_causes: causes,
    recommended_checks: checks,
  };
}

function recs(pairs) {
  return pairs.map(([title, probabilityPercent]) => ({ title, probabilityPercent }));
}

function chat(lines) {
  return lines.map(([sender, content]) => ({ sender, content }));
}

/**
 * Заявки «не Ивана»: очередь менеджера и общая очередь админа выглядят по-разному.
 * `assigned: false` — без ответственного (видят оба, в «Мои» у Марины нет).
 */
export function buildFleetCases({ hoursAgo, hoursFromNow, people, vehicles }) {
  const { managerId, anna, sergey, maria, dmitry, elena } = people;

  return [
    {
      assigned: false,
      status: 'NEW',
      make: 'Mercedes-Benz',
      model: 'E-Class',
      year: 2016,
      mileage: 148000,
      symptoms: 'Перегрев, пар идёт из-под капота',
      conditions: 'Пробка, жара, стрелка температуры в красной зоне',
      progressPercent: 100,
      confidencePercent: 82,
      costFromMinor: 18000,
      preliminaryNote: 'Срочно: не глушить на ходу, дотянуть до поста на аварийке. Вероятен термостат или помпа.',
      recommendations: recs([
        ['Заклинивший термостат — перегрев в пробке, пар из расширительного', 82],
        ['Помпа / течь патрубка системы охлаждения', 54],
        ['Забитый радиатор или крышка расширительного бачка', 31],
      ]),
      diagnosis: dx({
        summary:
          'По Mercedes E-Class 2016 пар и красная зона в пробке — не «просто долить воду». Сначала остывание, уровень и герметичность, затем термостат и помпа. До поста не открывайте крышку на горячую.',
        urgency: 'high',
        confidence: 0.82,
        cost: 4500,
        causes: [
          'Заклинивший термостат — перегрев в пробке, пар из расширительного',
          'Помпа / течь патрубка системы охлаждения',
          'Забитый радиатор или крышка расширительного бачка',
        ],
        checks: [
          'Дождаться остывания, проверить уровень и цвет антифриза',
          'Осмотр патрубков, помпы и радиатора на течь',
          'Диагностика термостата и пробки бачка',
        ],
      }),
      messages: chat([
        ['USER', 'Е-класс 2016, из-под капота пар, температура в красной зоне.'],
        ['ASSISTANT', 'Едете сейчас? Можно остановиться в безопасном месте?'],
        ['USER', 'Стою в пробке на МКАД, аварийка включена.'],
        ['ASSISTANT', 'Не открывайте крышку на горячую. Ориентир — термостат или помпа. Нужна срочная запись, заявку уже видит смена.'],
      ]),
      followUps: [],
      booking: null,
      createdAt: hoursAgo(2.2),
      guest: { name: 'Гость Игорь', phone: '+79995550101', email: 'igor.guest@example.local' },
    },
    {
      clientId: anna.id,
      vehicleId: vehicles.annaCrv?.id,
      assignedManagerId: managerId,
      status: 'NEW',
      make: 'Honda',
      model: 'CR-V',
      year: 2017,
      mileage: 112000,
      symptoms: 'Свист ремня на холодную',
      conditions: 'Утро, первые 2–3 минуты',
      progressPercent: 100,
      confidencePercent: 74,
      costFromMinor: 6500,
      preliminaryNote: 'Похоже на износ ремня навесного или ролик. Не срочно, но не тянуть до дождя.',
      recommendations: recs([
        ['Износ поликлинового ремня — свист только на холодную', 74],
        ['Ролик натяжителя', 48],
        ['Попадание антифриза/масла на ремень', 22],
      ]),
      diagnosis: dx({
        summary:
          'По Honda CR-V 2017 утренний свист на холодную почти всегда ремень навесного или ролик. На посту снимем пыльник и оценим глазурь и люфт ролика.',
        urgency: 'low',
        confidence: 0.74,
        cost: 2800,
        causes: ['Износ поликлинового ремня — свист только на холодную', 'Ролик натяжителя', 'Попадание антифриза/масла на ремень'],
        checks: ['Осмотр ремня на глазурь и трещины', 'Люфт и шум ролика', 'Течи с верхних узлов на ремень'],
      }),
      messages: chat([
        ['USER', 'CR-V, по утрам свистит ремень секунд тридцать.'],
        ['ASSISTANT', 'Свист пропадает после прогрева? Был дождь?'],
        ['USER', 'Да, только на холодную, вчера после мойки громче.'],
        ['ASSISTANT', 'Скорее ремень или ролик. Можно ехать, запись не экстренная.'],
      ]),
      followUps: ['Анна, добрый день! Можем принять CR-V завтра после 10:00 на замену ремня.'],
      booking: {
        preferredAt: hoursFromNow(20),
        status: 'PENDING',
        notes: 'Ремень навесного, пост 3',
      },
      createdAt: hoursAgo(0.6),
      firstResponseAt: hoursAgo(0.35),
    },
    {
      clientId: sergey.id,
      vehicleId: vehicles.sergeyA6?.id,
      assignedManagerId: managerId,
      status: 'IN_PROGRESS',
      make: 'Audi',
      model: 'A6',
      year: 2015,
      mileage: 189000,
      symptoms: 'Рывки DSG в пробке',
      conditions: 'Прогретая коробка, 1–2 передача',
      progressPercent: 100,
      confidencePercent: 68,
      costFromMinor: 28000,
      preliminaryNote: 'DSG: масло/адаптация. Оценка ИИ ещё не проставлена — висит в качестве.',
      recommendations: recs([
        ['Старое масло DSG — рывки 1–2 в пробке после прогрева', 68],
        ['Износ сцепления DQ250 / мехатроник', 41],
        ['Адаптация после нештатного отключения АКБ', 24],
      ]),
      diagnosis: dx({
        summary:
          'По Audi A6 2015 рывки DSG в пробке на 189 тыс. без истории масла — сначала сервис коробки и адаптация, не сразу мехатроник. На посту считаем DSG-коды и смотрим ATF.',
        urgency: 'medium',
        confidence: 0.68,
        cost: 8000,
        causes: [
          'Старое масло DSG — рывки 1–2 в пробке после прогрева',
          'Износ сцепления DQ250 / мехатроник',
          'Адаптация после нештатного отключения АКБ',
        ],
        checks: ['Ошибки DSG и счётчики пробуксовки', 'Состояние и запах масла', 'Тест-драйв 1–2 после прогрева'],
      }),
      messages: chat([
        ['USER', 'A6 2015 S-tronic, в пробке дёргается на 1-2.'],
        ['ASSISTANT', 'Масло в коробке когда меняли?'],
        ['USER', 'Дилер сказал «необслуживаемая», не менял.'],
        ['ASSISTANT', 'Для DSG это типичный миф. Сначала диагностика и замена масла с адаптацией.'],
      ]),
      followUps: [
        'Сергей, записали A6 на диагностику DSG. Не крутите селектор в ручной режим в пробке до визита.',
        'Нужен VIN с СТС — сверим тип коробки DQ250/DQ500.',
      ],
      booking: {
        preferredAt: hoursFromNow(28),
        status: 'CONFIRMED',
        notes: 'Диагностика DSG, пост 1',
      },
      createdAt: hoursAgo(16),
      firstResponseAt: hoursAgo(15.5),
    },
    {
      clientId: maria.id,
      vehicleId: vehicles.mariaRx?.id,
      assignedManagerId: managerId,
      status: 'COMPLETED',
      make: 'Lexus',
      model: 'RX',
      year: 2018,
      mileage: 76000,
      symptoms: 'Вибрация при торможении с трассы',
      conditions: 'После 110 км/ч',
      progressPercent: 100,
      confidencePercent: 80,
      costFromMinor: 24000,
      preliminaryNote: 'Диски поведены. Работы закрыты, оценка ИИ — верно.',
      recommendations: recs([
        ['Биение передних дисков после трассы', 80],
        ['Направляющие суппорта', 36],
      ]),
      diagnosis: dx({
        summary:
          'По Lexus RX 2018 вибрация после трассы — классика поведённых дисков. На посту промерили биение, заменили диск+колодки.',
        urgency: 'medium',
        confidence: 0.8,
        cost: 12000,
        causes: ['Биение передних дисков после трассы', 'Направляющие суппорта'],
        checks: ['Биение диска индикатором', 'Толщина колодок', 'Ход направляющих'],
      }),
      messages: chat([
        ['USER', 'RX, после трассы руль трясёт при торможении.'],
        ['ASSISTANT', 'С какой скорости начинаете тормозить, когда чувствуете биение?'],
        ['USER', 'Со 110–120.'],
      ]),
      followUps: ['Мария, работы закрыты: диски и колодки. Можно забирать после 18:00, заказ-наряд в кабинете.'],
      booking: {
        preferredAt: hoursAgo(6),
        status: 'CONFIRMED',
        notes: 'Выполнено, выдача вечером',
      },
      createdAt: hoursAgo(52),
      firstResponseAt: hoursAgo(51),
      feedback: {
        managerId,
        verdict: 'CORRECT',
        actualCause: 'Биение передних тормозных дисков',
        worksDone: 'Замена передних дисков и колодок, смазка направляющих',
        repairAmountMinor: 28600,
        workOrderNumber: 'ЗН-10442',
        repairCompletedAt: hoursAgo(7),
      },
    },
    {
      clientId: dmitry.id,
      vehicleId: vehicles.dmitryOutlander?.id,
      assignedManagerId: managerId,
      status: 'COMPLETED',
      make: 'Mitsubishi',
      model: 'Outlander',
      year: 2014,
      mileage: 201000,
      symptoms: 'Гул на скорости, думали ступичный',
      conditions: 'Трасса 90–110',
      progressPercent: 100,
      confidencePercent: 61,
      costFromMinor: 12000,
      preliminaryNote: 'ИИ указал ступичный, по факту — шины. Оценка: неверно.',
      recommendations: recs([
        ['Ступичный подшипник справа', 61],
        ['Износ шины / грыжа', 33],
      ]),
      diagnosis: dx({
        summary:
          'По Outlander 2014 гул на трассе ИИ склонял к ступичному. На подъёмнике люфта не было — виновник комплект резины.',
        urgency: 'medium',
        confidence: 0.61,
        cost: 4000,
        causes: ['Ступичный подшипник справа', 'Износ шины / грыжа'],
        checks: ['Люфт ступицы', 'Температура ступиц', 'Осмотр шин'],
      }),
      messages: chat([
        ['USER', 'Аутлендер, гул справа на сотке. Похоже на подшипник?'],
        ['ASSISTANT', 'Гул сильнее в повороте влево?'],
        ['USER', 'Вроде да, но не уверен.'],
      ]),
      followUps: ['Дмитрий, ступицы живые. Гул даёт износ внутренней дорожки шин. Рекомендуем комплект и сход-развал.'],
      booking: {
        preferredAt: hoursAgo(40),
        status: 'CONFIRMED',
        notes: 'Диагностика ходовой, без замены ступицы',
      },
      createdAt: hoursAgo(90),
      firstResponseAt: hoursAgo(89),
      feedback: {
        managerId,
        verdict: 'INCORRECT',
        actualCause: 'Гребёнка и износ внутренней дорожки шин, ступицы без люфта',
        worksDone: 'Диагностика ходовой, рекомендации по шинам и развалу',
        repairAmountMinor: 4500,
        workOrderNumber: 'ЗН-10391',
        repairCompletedAt: hoursAgo(38),
      },
    },
    {
      clientId: elena.id,
      vehicleId: vehicles.elenaTiguan?.id,
      assignedManagerId: managerId,
      status: 'SCHEDULED',
      make: 'Volkswagen',
      model: 'Tiguan',
      year: 2019,
      mileage: 84000,
      symptoms: 'Плановое ТО 80 тыс.',
      conditions: 'Регламент',
      progressPercent: 100,
      confidencePercent: 92,
      costFromMinor: 14500,
      preliminaryNote: 'ТО-80: масло, фильтры, DSG-интервал под вопросом.',
      recommendations: recs([
        ['Регламент ТО-80: масло ДВС и фильтры', 92],
        ['Проверка интервала DSG', 60],
      ]),
      diagnosis: dx({
        summary:
          'По Tiguan 2019 на 84 тыс. это регламентное ТО плюс сверка DSG. Неисправности нет, слот подтверждён.',
        urgency: 'low',
        confidence: 0.92,
        cost: 9000,
        causes: ['Регламент ТО-80: масло ДВС и фильтры', 'Проверка интервала DSG'],
        checks: ['Книжка и интервалы VAG', 'Уровень DSG', 'Тормоза и жидкости'],
      }),
      messages: chat([
        ['USER', 'Тигуан, пора ТО, пробег 84 тысячи.'],
        ['ASSISTANT', 'Делаем полный комплект и проверим, не подошло ли масло DSG.'],
        ['USER', 'Да, давайте сразу.'],
      ]),
      followUps: ['Елена, ТО подтверждено на послезавтра 09:30. Возьмите сервисную книжку.'],
      booking: {
        preferredAt: hoursFromNow(42),
        status: 'CONFIRMED',
        notes: 'ТО-80 + проверка DSG',
      },
      createdAt: hoursAgo(22),
      firstResponseAt: hoursAgo(21),
    },
    {
      assigned: false,
      status: 'NEW',
      make: 'Toyota',
      model: 'Land Cruiser',
      year: 2013,
      mileage: 240000,
      symptoms: 'Не включается полный привод, ошибка 4WD',
      conditions: 'Грязь, после брода',
      progressPercent: 95,
      confidencePercent: 57,
      costFromMinor: 19000,
      preliminaryNote: 'Без ответственного. Возможна муфта или датчик. SLA уже горит.',
      recommendations: recs([
        ['Муфта включения переднего моста после брода', 57],
        ['Датчик / актуатор раздатки', 44],
        ['Ошибка блока 4WD, нужна компьютерная диагностика', 40],
      ]),
      diagnosis: dx({
        summary:
          'По Land Cruiser 2013 отказ 4WD после брода — сначала диагностика блока и актуатора, не сразу разбор моста. Заявка без ответственного.',
        urgency: 'medium',
        confidence: 0.57,
        cost: 5000,
        causes: [
          'Муфта включения переднего моста после брода',
          'Датчик / актуатор раздатки',
          'Ошибка блока 4WD, нужна компьютерная диагностика',
        ],
        checks: ['Коды 4WD', 'Актуатор и проводка', 'Состояние муфты после воды'],
      }),
      messages: chat([
        ['USER', 'Крузак, после брода не цепляет полный привод, на панели 4WD.'],
        ['ASSISTANT', 'Горит постоянно или мигает? Машина на ходу?'],
        ['USER', 'Горит постоянно, еду на заднем.'],
      ]),
      followUps: [],
      booking: null,
      createdAt: hoursAgo(4),
      guest: { name: 'Гость Никита', phone: '+79995550102' },
    },
    {
      guest: { name: 'Гость Светлана', phone: '+79995550103', email: 'svetlana.guest@example.local' },
      assignedManagerId: managerId,
      status: 'IN_PROGRESS',
      make: 'Chery',
      model: 'Tiggo 7 Pro',
      year: 2022,
      mileage: 28000,
      symptoms: 'Кондиционер пахнет и слабо холодит',
      conditions: 'Город, жара',
      progressPercent: 100,
      confidencePercent: 63,
      costFromMinor: 8500,
      preliminaryNote: 'Гостевая в работе у Марины. Испаритель / фреон. Оценки ИИ нет.',
      recommendations: recs([
        ['Бактерии на испарителе — запах при включении СК', 63],
        ['Нехватка фреона', 49],
        ['Салонный фильтр', 35],
      ]),
      diagnosis: dx({
        summary:
          'По Chery Tiggo запах и слабый холод — антибактериальная обработка испарителя плюс замер фреона, не только фильтр.',
        urgency: 'low',
        confidence: 0.63,
        cost: 3500,
        causes: ['Бактерии на испарителе — запах при включении СК', 'Нехватка фреона', 'Салонный фильтр'],
        checks: ['Салонный фильтр', 'Давления фреона', 'Обработка испарителя'],
      }),
      messages: chat([
        ['USER', 'Тигго, кондиционер пахнет сыростью и дует еле холодным.'],
        ['ASSISTANT', 'Фильтр салона когда меняли?'],
        ['USER', 'Не помню, машине полтора года.'],
      ]),
      followUps: ['Светлана, приняли в работу. Завтра утром замерим фреон и обработаем испаритель.'],
      booking: {
        preferredAt: hoursFromNow(18),
        status: 'CONFIRMED',
        notes: 'СК: фреон + антибак',
      },
      createdAt: hoursAgo(9),
      firstResponseAt: hoursAgo(8.5),
    },
    {
      clientId: anna.id,
      vehicleId: vehicles.annaFocus?.id,
      assignedManagerId: managerId,
      status: 'CANCELLED',
      make: 'Ford',
      model: 'Focus',
      year: 2016,
      mileage: 134000,
      symptoms: 'Скрип тормозов, хотели колодки',
      conditions: 'Город',
      progressPercent: 80,
      confidencePercent: 70,
      costFromMinor: 8000,
      preliminaryNote: 'Клиент отменил: уехала в командировку.',
      recommendations: recs([['Износ передних колодок — скрип в городе', 70]]),
      diagnosis: dx({
        summary: 'По Focus 2016 городской скрип — колодки. Слот отменён, заявку можно открыть снова.',
        urgency: 'low',
        confidence: 0.7,
        cost: 3500,
        causes: ['Износ передних колодок — скрип в городе'],
        checks: ['Толщина колодок', 'Состояние дисков'],
      }),
      messages: chat([
        ['USER', 'Фокус, скрипят тормоза, запишите на колодки.'],
        ['ASSISTANT', 'Скрип на холодную или постоянно?'],
        ['USER', 'Постоянно. Но я на неделю уезжаю — давайте отменим.'],
      ]),
      followUps: ['Анна, слот сняли. Когда вернётесь — напишите, поставим колодки без новой консультации.'],
      booking: {
        preferredAt: hoursAgo(8),
        status: 'CANCELLED',
        notes: 'Командировка клиента',
      },
      createdAt: hoursAgo(36),
      firstResponseAt: hoursAgo(35),
    },
    {
      clientId: sergey.id,
      vehicleId: vehicles.sergeyGranta?.id,
      assigned: false,
      status: 'NEW',
      make: 'Lada',
      model: 'Granta',
      year: 2020,
      mileage: 61000,
      symptoms: 'Троит на холодную, запах бензина',
      conditions: 'Утро, минус на улице не было',
      progressPercent: 88,
      confidencePercent: 59,
      costFromMinor: 7000,
      preliminaryNote: 'Вторая машина Сергея, без ответственного. Возможны свечи/катушка.',
      recommendations: recs([
        ['Свеча / катушка — троение на холодную', 59],
        ['Форсунка', 34],
      ]),
      diagnosis: dx({
        summary:
          'По Granta 2020 троение и запах бензина на холодную — сначала свечи и катушки, не сразу рампа. Заявка ещё ничья.',
        urgency: 'medium',
        confidence: 0.59,
        cost: 2500,
        causes: ['Свеча / катушка — троение на холодную', 'Форсунка'],
        checks: ['Ошибки ЭБУ', 'Свечи и катушки', 'Подсос и форсунки'],
      }),
      messages: chat([
        ['USER', 'Ещё Гранта жены троит по утрам, пахнет бензином.'],
        ['ASSISTANT', 'Check Engine горит?'],
        ['USER', 'Мигает секунд десять, потом тухнет.'],
      ]),
      followUps: [],
      booking: null,
      createdAt: hoursAgo(1.1),
    },
  ];
}

export function buildFleetVehicles(people) {
  return [
    {
      key: 'ivanCamry',
      clientId: people.client.id,
      make: 'Toyota',
      model: 'Camry',
      year: 2018,
      vin: 'XT4BF3EK3JZ123456',
      licensePlate: 'А123ВС777',
      color: 'чёрный',
      currentMileageKm: 132000,
      notes: 'Основной автомобиль Ивана',
    },
    {
      key: 'ivanRio',
      clientId: people.client.id,
      make: 'Kia',
      model: 'Rio',
      year: 2019,
      vin: 'XWEPH81ABK0001122',
      licensePlate: 'О456КХ777',
      color: 'белый',
      currentMileageKm: 98000,
    },
    {
      key: 'ivanPolo',
      clientId: people.client.id,
      make: 'Volkswagen',
      model: 'Polo',
      year: 2020,
      vin: 'XW8ZZZ61ZLG045678',
      licensePlate: 'У888УУ777',
      color: 'серебристый',
      currentMileageKm: 64000,
    },
    {
      key: 'ivanQashqai',
      clientId: people.client.id,
      make: 'Nissan',
      model: 'Qashqai',
      year: 2013,
      vin: 'SJNFAAJ10U1234567',
      licensePlate: 'Х909ХХ777',
      color: 'тёмно-серый',
      currentMileageKm: 166000,
    },
    {
      key: 'annaCrv',
      clientId: people.anna.id,
      make: 'Honda',
      model: 'CR-V',
      year: 2017,
      vin: 'RUHRM4850H7003344',
      licensePlate: 'В789ОР777',
      color: 'синий',
      currentMileageKm: 112000,
    },
    {
      key: 'annaFocus',
      clientId: people.anna.id,
      make: 'Ford',
      model: 'Focus',
      year: 2016,
      vin: 'X9FMXXEEBKG123789',
      licensePlate: 'С321ТА199',
      color: 'серый',
      currentMileageKm: 134000,
    },
    {
      key: 'sergeyA6',
      clientId: people.sergey.id,
      make: 'Audi',
      model: 'A6',
      year: 2015,
      vin: 'WAUZZZ4G6FN045612',
      licensePlate: 'Е654УХ777',
      color: 'тёмно-синий',
      currentMileageKm: 189000,
    },
    {
      key: 'sergeyGranta',
      clientId: people.sergey.id,
      make: 'Lada',
      model: 'Granta',
      year: 2020,
      vin: 'XTA219010K0123456',
      licensePlate: 'К111КК150',
      color: 'белый',
      currentMileageKm: 61000,
      notes: 'Авто супруги',
    },
    {
      key: 'mariaRx',
      clientId: people.maria.id,
      make: 'Lexus',
      model: 'RX',
      year: 2018,
      vin: 'JTJBARBZ4J2123789',
      licensePlate: 'М007ММ777',
      color: 'белый перламутр',
      currentMileageKm: 76000,
    },
    {
      key: 'dmitryOutlander',
      clientId: people.dmitry.id,
      make: 'Mitsubishi',
      model: 'Outlander',
      year: 2014,
      vin: 'JMBXTGF3WEZ123450',
      licensePlate: 'Н555СН777',
      color: 'коричневый',
      currentMileageKm: 201000,
    },
    {
      key: 'elenaTiguan',
      clientId: people.elena.id,
      make: 'Volkswagen',
      model: 'Tiguan',
      year: 2019,
      vin: 'XW8ZZZ5NZKG012345',
      licensePlate: 'Р222РТ777',
      color: 'серый',
      currentMileageKm: 84000,
    },
    {
      key: 'olegPeugeot',
      clientId: people.oleg.id,
      make: 'Peugeot',
      model: '408',
      year: 2013,
      vin: 'VF34D5FS0DS123456',
      licensePlate: 'Т333ТТ199',
      color: 'красный',
      currentMileageKm: 176000,
      notes: 'Профиль клиента заблокирован',
    },
  ];
}

export function buildExtraBookings({ hoursAgo, hoursFromNow, people, vehicles }) {
  return [
    {
      clientId: people.anna.id,
      vehicleId: vehicles.annaCrv?.id,
      preferredAt: hoursFromNow(3),
      status: 'PENDING',
      notes: 'Перекидка шин CR-V, без заявки',
    },
    {
      clientId: people.maria.id,
      vehicleId: vehicles.mariaRx?.id,
      preferredAt: hoursAgo(1.2),
      status: 'ARRIVED',
      notes: 'Выдача RX после тормозов, клиент на территории',
    },
    {
      clientId: people.dmitry.id,
      vehicleId: vehicles.dmitryOutlander?.id,
      preferredAt: hoursAgo(26),
      status: 'NO_SHOW',
      notes: 'Предпродажный осмотр — неявка',
    },
    {
      clientId: people.elena.id,
      vehicleId: vehicles.elenaTiguan?.id,
      preferredAt: hoursFromNow(66),
      status: 'CONFIRMED',
      notes: 'Повторная диагностика через неделю после ТО',
    },
    {
      guestName: 'Гость Артём',
      guestPhone: '+79995550999',
      preferredAt: hoursFromNow(9),
      status: 'PENDING',
      notes: 'Осмотр перед покупкой Passat',
    },
    {
      clientId: people.sergey.id,
      vehicleId: vehicles.sergeyA6?.id,
      preferredAt: hoursFromNow(100),
      status: 'CONFIRMED',
      notes: 'Контроль DSG после замены масла',
    },
  ];
}

export function buildExtraContacts({ hoursAgo, convertedRequestId }) {
  return [
    {
      fullName: 'Игорь К.',
      phone: '+79995550101',
      message: 'Е-класс кипит на МКАД. Можно эвакуатор к вам?',
      source: 'contact_form',
      status: 'IN_PROGRESS',
      processedAt: hoursAgo(2),
      createdAt: hoursAgo(2.3),
    },
    {
      fullName: 'Светлана Р.',
      phone: '+79995550103',
      message: 'Запах из кондиционера Tiggo, можно без регистрации?',
      source: 'contact_form',
      status: 'CONVERTED',
      processedAt: hoursAgo(8),
      convertedRequestId: convertedRequestId || null,
      createdAt: hoursAgo(10),
    },
    {
      fullName: 'Павел Д.',
      phone: '+79990001212',
      message: 'Нужен акт осмотра для страховой, вы делаете?',
      source: 'contact_form',
      status: 'CLOSED',
      processedAt: hoursAgo(30),
      closedReason: 'Не наш профиль — направили к эксперту-оценщику',
      createdAt: hoursAgo(33),
    },
    {
      fullName: 'Алина В.',
      phone: '+79990001313',
      message: 'Есть ли у вас мойка двигателя? Camry после ремонта текла.',
      source: 'contact_form',
      status: 'NEW',
      createdAt: hoursAgo(1.4),
    },
    {
      fullName: 'Роман Г.',
      phone: '+79990001414',
      message: 'Хотим договор на 12 служебных авто, кто менеджер парка?',
      source: 'contact_form',
      status: 'NEW',
      createdAt: hoursAgo(6),
    },
    {
      fullName: 'Татьяна И.',
      phone: '+79990001515',
      message: 'Можно ли приехать в воскресенье на шиномонтаж?',
      source: 'contact_form',
      status: 'CLOSED',
      processedAt: hoursAgo(12),
      closedReason: 'Воскресенье выходной, предложили субботу',
      createdAt: hoursAgo(14),
    },
  ];
}

export const EXTRA_SCENARIOS = [
  {
    title: 'Тормоза и биение',
    description: 'Вибрация, скрип, увод — первичная консультация по тормозам',
    questions: [
      'На какой скорости появляется вибрация или скрип?',
      'Биение в руле, педали или кузове?',
      'Когда меняли колодки и диски?',
    ],
    hints: ['Спросить про трассу и перегрев', 'Не пугать отказом тормозов без фактов'],
  },
  {
    title: 'Подвеска и стуки',
    description: 'Стуки, гул ступицы, увод',
    questions: [
      'Стук глухой или звонкий, с какой стороны?',
      'На мелких кочках или ямах?',
      'Гул растёт со скоростью?',
    ],
    hints: ['Отличить стойку стабилизатора от ступицы', 'Спросить про недавний шиномонтаж'],
  },
  {
    title: 'Двигатель и Check Engine',
    description: 'Троение, расход, ошибки ЭБУ',
    questions: ['Горит или мигает Check Engine?', 'Троит на холодную или на горячую?', 'Считывали код ошибки?'],
    hints: ['Мигающий Check — не крутить мотор', 'Не ставить диагноз по одному симптому'],
  },
  {
    title: 'Электрика и АКБ',
    description: 'Разряд, утечка, генератор',
    questions: ['АКБ сколько лет?', 'Есть нештатное оборудование?', 'Садится за ночь или на ходу тухнет?'],
    hints: ['Сначала тест АКБ и ток покоя', 'Не предлагать сразу генератор'],
  },
];

export function buildOrphanConsultations({ hoursAgo, clientId }) {
  return [
    {
      clientId,
      status: 'ABANDONED',
      progressPercent: 20,
      flowState: { stage: 'COLLECTING_SYMPTOMS' },
      createdAt: hoursAgo(14),
      messages: [
        { sender: 'ASSISTANT', content: 'Опишите марку, модель и что случилось.' },
        { sender: 'USER', content: 'Camry… сейчас за рулём, продолжу вечером.' },
      ],
      extracted: { make: 'Toyota', model: 'Camry', year: 2018 },
    },
    {
      clientId: null,
      guestName: 'Гость без заявки',
      guestPhone: '+79995550888',
      status: 'AI_ERROR',
      progressPercent: 55,
      flowState: { stage: 'CLARIFYING', error: 'LLM_TIMEOUT' },
      createdAt: hoursAgo(7),
      messages: [
        { sender: 'USER', content: 'Passat 2012, стук гидрокомпенсаторов на холодную.' },
        { sender: 'SYSTEM', content: 'Интеллектуальный модуль не ответил вовремя. Можно повторить запрос.' },
      ],
      extracted: { make: 'Volkswagen', model: 'Passat', year: 2012, symptoms: 'Стук на холодную' },
    },
    {
      clientId,
      status: 'COMPLETED',
      progressPercent: 100,
      confidencePercent: 70,
      costFromMinor: 4000,
      preliminaryNote: 'Клиент сохранил отчёт, заявку не оформлял.',
      flowState: { stage: 'COMPLETED' },
      createdAt: hoursAgo(60),
      messages: [
        { sender: 'USER', content: 'Интересно было проверить, как ИИ отвечает. Polo, плавают обороты — уже чинили.' },
        { sender: 'ASSISTANT', content: 'Похоже на дроссель. Если уже чинили и всё стабильно — заявку можно не создавать.' },
      ],
      extracted: { make: 'Volkswagen', model: 'Polo', year: 2020, symptoms: 'Плавающие обороты (повтор)' },
    },
  ];
}

export const EXTRA_CMS_BLOCKS = [
  {
    key: 'home.promo.brakes',
    title: 'Акция на тормоза',
    section: 'home',
    content: 'До конца месяца диагностика тормозов −15%. Черновик, не публиковать без согласования.',
    isPublished: false,
  },
  {
    key: 'contacts.evacuation',
    title: 'Эвакуатор',
    section: 'contacts',
    content: 'Эвакуатор по Москве и МО: +7 999 000-00-10, круглосуточно для перегрева и ДВС.',
    isPublished: true,
  },
];
